# Data Cleaning workflow

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
import pandas as pd
import numpy as np
from datetime import timedelta as td
from DataAnalyst.precise import Precise, Tracer, extract_villages
import warnings
warnings.simplefilter(action='ignore', category=UserWarning)

In [3]:
anc_dir=r"./surveillance"
gambia_dir=os.path.join(anc_dir, "Gambia")
kenya_dir=os.path.join(anc_dir, "Kenya")
mozambique_dir=os.path.join(anc_dir, "Mozambique")

In [ ]:
# gambia=Precise("Gambia", gambia_dir)

In [14]:
kenya=Precise("Kenya", kenya_dir)

C:\Users\s1465450\OneDrive - University of Edinburgh\personal_training\precisehealthgeo\DataAnalyst\precise.py:61: DtypeWarning: Columns (295) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv(self.filepath.format(visit_num), usecols=cols, index_col='f2a_participant_id')
C:\Users\s1465450\OneDrive - University of Edinburgh\personal_training\precisehealthgeo\DataAnalyst\precise.py:61: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv(self.filepath.format(visit_num), usecols=cols, index_col='f2a_participant_id')

In [4]:
# mozambique=Precise("Mozambique", mozambique_dir)

In [15]:
# tracer is applied to Kenya and The Gambia only
tracer=Tracer("Kenya", os.path.join(anc_dir, "TRACER_GA_estimates_11_11_22.csv"))
tracer.formatDates()

In [18]:
df1=(kenya.dropDuplicates()
 .mergeData()
 .formatDates()
 .addTracer(tracer)
 .calculate_gestation()
 .pregnancy_location() # .facility_location()
 .export_bigTable('village'))

In [19]:
df1

                                      conception_date delivery_date  \
f2a_participant_id exposure_month
254-40004          2018_12        2018-12-16 17:02:24    2019-09-17
                   2019_01        2018-12-16 17:02:24    2019-09-17
                   2019_02        2018-12-16 17:02:24    2019-09-17
                   2019_03        2018-12-16 17:02:24    2019-09-17
                   2019_04        2018-12-16 17:02:24    2019-09-17
...                                               ...           ...
254-92532          2022_05        2021-12-10 00:00:00    2022-09-03
                   2022_06        2021-12-10 00:00:00    2022-09-03
                   2022_07        2021-12-10 00:00:00    2022-09-03
                   2022_08        2021-12-10 00:00:00    2022-09-03
                   2022_09        2021-12-10 00:00:00    2022-09-03

                                  village_code
f2a_participant_id exposure_month
254-40004          2018_12            MWELE_B
                   2019_01            MWELE_B
                   2019_02            MWELE_B
                   2019_03            MWELE_B
                   2019_04            MWELE_B
...                                        ...
254-92532          2022_05           KINANI_B
                   2022_06           KINANI_B
                   2022_07           KINANI_A
                   2022_08           KINANI_A
                   2022_09           KINANI_A

[16502 rows x 3 columns]

In [20]:
dff=pd.merge(df1, df2.drop(columns='conception_date'), left_index=True, right_index=True, how='inner', validate='1:1')
dff

                                      conception_date delivery_date_x  \
f2a_participant_id exposure_month
254-40004          2018_12        2018-12-16 17:02:24      2019-09-17
                   2019_01        2018-12-16 17:02:24      2019-09-17
                   2019_02        2018-12-16 17:02:24      2019-09-17
                   2019_03        2018-12-16 17:02:24      2019-09-17
                   2019_04        2018-12-16 17:02:24      2019-09-17
...                                               ...             ...
254-92532          2022_05        2021-12-10 00:00:00      2022-09-03
                   2022_06        2021-12-10 00:00:00      2022-09-03
                   2022_07        2021-12-10 00:00:00      2022-09-03
                   2022_08        2021-12-10 00:00:00      2022-09-03
                   2022_09        2021-12-10 00:00:00      2022-09-03

                                  village_code delivery_date_y facility_code
f2a_participant_id exposure_month
254-40004          2018_12            MWELE_B       2019-09-17        Rabai
                   2019_01            MWELE_B       2019-09-17        Rabai
                   2019_02            MWELE_B       2019-09-17        Rabai
                   2019_03            MWELE_B       2019-09-17        Rabai
                   2019_04            MWELE_B       2019-09-17        Rabai
...                                        ...             ...           ...
254-92532          2022_05           KINANI_B       2022-09-03     Mariakani
                   2022_06           KINANI_B       2022-09-03     Mariakani
                   2022_07           KINANI_A       2022-09-03     Mariakani
                   2022_08           KINANI_A       2022-09-03     Mariakani
                   2022_09           KINANI_A       2022-09-03     Mariakani

[16481 rows x 5 columns]

In [ ]:
dff.drop(columns='delivery_date_y').rename(columns={'delivery_date_x': 'delivery_date'}).to_csv(os.path.join(anc_dir, "Kenya", "pregnancy_facility_location.csv"))

In [42]:
def str_format(x):
    return (x.replace('_', ' ')
            .replace('-', ' ')
            .upper()
            .strip())

In [45]:
dff=pd.read_csv(os.path.join(anc_dir, "Kenya", "pregnancy_facility_location.csv"))
dff['village_code']=dff['village_code'].map(str_format)
dff['village_code']=dff['village_code'].map(codes)
dff

,f2a_participant_id,exposure_month,conception_date,delivery_date,village_code,facility_code
0,254-40004,2018_12,2018-12-16 17:02:24.000000000,2019-09-17,254062.0,Rabai
1,254-40004,2019_01,2018-12-16 17:02:24.000000000,2019-09-17,254062.0,Rabai
2,254-40004,2019_02,2018-12-16 17:02:24.000000000,2019-09-17,254062.0,Rabai
3,254-40004,2019_03,2018-12-16 17:02:24.000000000,2019-09-17,254062.0,Rabai
4,254-40004,2019_04,2018-12-16 17:02:24.000000000,2019-09-17,254062.0,Rabai
...,...,...,...,...,...,...
16476,254-92532,2022_05,2021-12-10 00:00:00.000000000,2022-09-03,NaN,Mariakani
16477,254-92532,2022_06,2021-12-10 00:00:00.000000000,2022-09-03,NaN,Mariakani
16478,254-92532,2022_07,2021-12-10 00:00:00.000000000,2022-09-03,NaN,Mariakani
16479,254-92532,2022_08,2021-12-10 00:00:00.000000000,2022-09-03,NaN,Mariakani
16480,254-92532,2022_09,2021-12-10 00:00:00.000000000,2022-09-03,NaN,Mariakani

In [47]:
dff.to_csv(os.path.join(anc_dir, "Kenya", "pregnancy_facility_location.csv"))

In [ ]:
# gambia.getCohort(drop_abnormal=True)

In [ ]:
# df=gambia.getSocialIndicators()

In [ ]:
# df.to_csv(os.path.join(root_dir, 'gambia/socio_geo.csv'))

In [ ]:
# from sqlalchemy import create_engine

In [ ]:
# # engine=create_engine("postgresql://postgres:PRECISE2021@10.85.0.115/precise")
# engine=create_engine("postgresql://postgres:Pumkin987!@127.0.0.1/precise")
# df.to_sql("socio_geo", engine, schema="gambia", index=True, if_exists="append")

In [ ]:
# mozambique_df=mozambique.getCohort(drop_abnormal=False).drop(columns=['f3_neighbor_help_pregnancy_problem', 'f3_form_of_help_received', 'f3_community_help_pregnancy_problem', 
#                                                       'f3_participation_in_community_group', 'f3_decision_maker_money', 'f3_decision_maker_pregnancy', 'f3_woman_has_money_for_transport', 
#                                                       'gestation', 
#                                                                       'months', 
#                                                                       'tracer_ga', 'tracer_visit_date', 
#                                                                       'f2_visit_date_visit_1', 'f2_visit_date_visit_2', 
#                                                       'f2_ga_at_visit_visit_1',	'f2_ga_at_visit_visit_2', 'f2_ga_at_visit_visit_3', 'f2_health_facility_visit_1', 'f2_health_facility_visit_2', 
#                                                       'f2_health_facility_visit_3', 
#                                                                       'f2_village_visit_1', 'f2_village_visit_2', 'f2_village_visit_3', 
#                                                                       'f2a_cohort', 'f3_highest_school_level', 
#                                                       'f3_religion', 'f3_marital_status', 'f3_live_with_partner', 'f3_occupation', 'f3_duration_of_living_together', 'f3_year_of_birth', 'f3_toilet_facility'])

In [ ]:
# mozambique_df=(mozambique_df.rename(columns={'f2_visit_date_visit_3': 'delivery_date'})
#            .reset_index()
#            .dropna(subset=['conception_date', 'delivery_date'])
#            .melt(id_vars=['f2a_participant_id', 'conception_date', 'delivery_date'], var_name='exposure_month', value_name='neighborhood_code', ignore_index=True)
#            .sort_values(by=['f2a_participant_id', 'exposure_month'])
#            .dropna()
#            .set_index(['f2a_participant_id', 'exposure_month']))
# mozambique_df

In [ ]:
# mozambique_df.to_csv(os.path.join(root_dir, 'mozambique/pregnancy_locations.csv'))

In [ ]:
# mozambique_villages=mozambique_df.reset_index().sort_values(by='village_code').drop_duplicates(subset=['village_code'], keep='first')
# mozambique_villages[['village_code']].to_csv(os.path.join(root_dir, 'mozambique/mozambique_unique_villages.csv'))

In [ ]:
# def extract_villages(dict_path, anc_path, country, out_path, neigh_path):    
#     #function for mapping locality codes to string names
#     def remap(row, prefix):
#         if isinstance(row['select_choices_or_calculations'], str):
#             localities=dict()
#             for locality in row['select_choices_or_calculations'].split('|'):
#                 k, *v=locality.split(',')
#                 localities[int(k)]=','.join(v) if isinstance(v, list) else v.strip()
#             row[prefix]=localities
#         else:
#             #dealing with villages in 'dont know' columns
#             row[prefix]={0: np.nan, 1: np.nan}
#         return row    
#     #function for collapsing individual localities into single column
#     def set_locality(df, **data_dict):
#         for key, value in data_dict.items():
#             for k, v in value.items():
#                 if not k.endswith('other_name') and k in df.columns:
#                     df[k]=df[k].map(v)
#             df[key]=(df.filter([k for k in data_dict[key].keys()], axis=1)
#                      .apply(lambda x: max(x.dropna()) if x.dropna().any() else np.nan, axis=1))
#         return df
#     # #function for collapsing individual localities into single column
#     # def set_locality(df):
#     #     for k in df.filter(like='f2_mz_n'):
#     #         if not k.endswith('other_name'):
#     #                 df[k]=df[k].replace(range(101), np.nan)
#     #     df['f2_mz_n']=(df.filter(like='f2_mz_n', axis=1)
#     #                    .apply(lambda x: max(x.dropna()) if x.dropna().any() else np.nan, axis=1))
#     #     return df
    
#     data_dict=pd.read_csv(dict_path, index_col=0) 
#     # creating a nested dictionary containing dictionaries of the localities        
#     prefixes=['f2_ke_v', 'f2_ke_chu', 'f2_ke_link', 'f2_ke_county', 'f2_ke_sub_county', 'f2_ke_health']
#     # prefixes=['f2_mz_n', 'f2_mz_loc', 'f2_mz_admin', 'f2_mz_health']
#     final_dictionary=dict()
#     for p in prefixes:
#         final_dictionary.update(data_dict.filter(like=p, axis=0)[["select_choices_or_calculations"]]
#                                 .apply(lambda x: remap(x, p), axis=1)[[p]]
#                                 .to_dict())   
        
#     neighborhood_codes=pd.read_csv(neigh_path)     
#     #code to run for all the 3 visits at the same time.
#     for i in range(1, 4):
#         anc_df=pd.read_csv(os.path.join(anc_path, r'Visit{}_v2.csv'.format(i))) 
#         # anc_df=(set_locality(anc_df)
#         #        .rename(columns={'f2_mz_n': 'f2_mz_village'}))
#         anc_df=(set_locality(anc_df, **final_dictionary)
#                .rename(columns={'f2_ke_v': 'f2_ke_village', 'f2_ke_link': 'f2_ke_link_facility', 'f2_ke_health': 'f2_ke_health_facility'}))
#                # .rename(columns={'f2_mz_n': 'f2_mz_nbr', 'f2_mz_health': 'f2_mz_health_facility'})
#                # .merge(neighborhood_codes, on=['f2_mz_nbr', 'f2_mz_loc', 'f2_mz_admin'], how='left', validate='m:m'))   
#         anc_df.to_csv(os.path.join(out_path, r'Visit{}_v2.csv'.format(i)))
#     return

In [22]:
import geopandas as gpd

In [24]:
shps=gpd.read_file(r'shapefiles/precise_villages.gpkg', layer='kenya_neighborhoods')

In [28]:
codes=dict(zip(shps['name'], shps['neighborhood_code']))

In [36]:
codes

{'BATANI': 254001,
 'BATANI ASILI': 254002,
 'BENGO MWARENI': 254003,
 'BOFU': 254004,
 'BONJE': 254005,
 'BUNI KIBAONI A': 254006,
 'BUNI KIBAONI B': 254007,
 'BUNI KISWARINI': 254008,
 'DAMVIEW': 254131,
 'DETENI': 254133,
 'DZIHOSHE A': 254009,
 'FOREST': 254011,
 'JAKABA': 254013,
 'JIMBA MSIKITINI': 254015,
 'JITENGE': 254016,
 'KADZANDANI A': 254017,
 'KADZONZO A': 254019,
 'KAILO MNYALANI': 254021,
 'KAKUNAA': 254022,
 'KALIANGOMBE A': 254023,
 'KAMKOMANI': 254024,
 'KANYUMBUNI': 254164,
 'KATOLANI': 254025,
 'KIBANDA HASARA': 254027,
 'KIBAONI': 254028,
 'KIBOJONI': 254029,
 'KINOU': 254030,
 'KIPEVU MBAA': 254031,
 'KISURUTINI BUKINI': 254032,
 'KITSAMANI': 254033,
 'KIVUNGA': 254184,
 'KOKOTONI': 254185,
 'KWA KAJETA': 254035,
 'KWA KIJALA': 254036,
 'KWA MDIGO': 254037,
 'LA MWAJOHA': 254038,
 'LUTSANGANI': 254039,
 'MADZIMBANI A': 254040,
 'MAJENGO': 254041,
 'MAKABURINI': 254042,
 'MAUNGONI VUGA': 254043,
 'MAVARATA': 254229,
 'MAZERAS': 254232,
 'MBARAKANI A': 254044,
 'MBARAKANI B': 254045,
 'MBUNGONI': 254238,
 'MBUYUNI': 254046,
 'MGANA': 254047,
 'MIGUNDINI': 254048,
 'MIKOMANI': 254049,
 'MIRACLE': 254050,
 'MISUFINI': 254051,
 'MKILO': 254250,
 'MKWAJUNI': 254052,
 'MKWAJUNI B': 254053,
 'MTSARANI': 254055,
 'MWANZAGU': 254057,
 'MWARENI A': 254058,
 'MWATSAMA': 254060,
 'MWELE A': 254061,
 'MWELE B': 254062,
 'NDATANI 3': 254063,
 'NGULUWENI': 254064,
 'NJORO MADZIMBINI': 254066,
 'NJORO TAKATIFU': 254067,
 'NYAHINI 1': 254068,
 'RABAI POWER': 254298,
 'SHANGIA': 254069,
 'SHIKAADABU': 254306,
 'SIMAKENI A': 254070,
 'SIMAKENI B': 254071,
 'TABORA': 254072,
 'VIZIANI': 254074,
 'VUMA': 254075}

# Extracting village names
The following functions process raw neighborhood/village_code columns in Kenya and Mozambique files to generate a village_name column

In [ ]:
kenya=os.path.join(anc_dir, "Kenya")
kenya_dict=os.path.join(kenya, "Kenya_data_dictionary.csv")
moza=os.path.join(anc_dir, "Mozambique")
moza_dict=os.path.join(moza, "Mozambique_data_dictionary.csv")

In [ ]:
extract_villages(moza_dict, moza, "Mozambique", out_dir, neigh_path)

In [ ]:
import geopandas as gpd

In [ ]:
village=gpd.read_file(os.path.join(root_dir, 'mozambique/shapefiles/mozambique_neighborhoods.geojson'), encoding='utf-8')
village

In [ ]:
mozambique_villages=pd.read_csv(os.path.join(root_dir, 'mozambique/mozambique_villages_women.csv'))
mozambique_villages

In [ ]:
village_mapping=pd.merge(village, dff3, on='neighborhood_code', how='inner', validate='1:m')[['neighborhood_code', 'f2_mz_nbr', 'f2_mz_loc', 'f2_mz_admin']]
# village_mapping.to_csv(os.path.join(root_dir, 'mozambique/shapefiles/mozambique_neighborhood_codes.csv'))
# village_mapping

In [ ]:
village.plot()

In [ ]:
mozambique_df

In [ ]:
df1=pd.read_csv(os.path.join(out_dir, "Visit1_v2.csv"), usecols=['f2a_participant_id', 'f2_mz_nbr', 'f2_mz_loc', 'f2_mz_admin', 'f2_mz_health_facility', 'f2_mz_village'])
df2=pd.read_csv(os.path.join(out_dir, "Visit2_v2.csv"), usecols=['f2a_participant_id', 'f2_mz_nbr', 'f2_mz_loc', 'f2_mz_admin', 'f2_mz_health_facility', 'f2_mz_village'])
df3=pd.read_csv(os.path.join(out_dir, "Visit3_v2.csv"), usecols=['f2a_participant_id', 'f2_mz_nbr', 'f2_mz_loc', 'f2_mz_admin', 'f2_mz_health_facility', 'f2_mz_village'])

In [ ]:
# dff=(pd.concat([df1.drop(columns='f2a_participant_id'), df2.drop(columns='f2a_participant_id'), df3.drop(columns='f2a_participant_id')], ignore_index=True).drop_duplicates(keep='first')
#     .sort_values(by=['f2_ke_village', 'f2_ke_chu', 'f2_ke_sub_county'])
#     .drop_duplicates(subset=['f2_ke_village', 'f2_ke_chu'])
#     .dropna())
# dff

In [ ]:
dff=(pd.concat([df1, df2, df3], ignore_index=True)
     # .drop_duplicates(keep='first')
     .dropna(subset=['f2_mz_nbr', 'f2_mz_loc', 'f2_mz_admin'])
     .sort_values(by=['f2_mz_nbr', 'f2_mz_loc', 'f2_mz_admin']))
dff

In [ ]:
dff2=(pd.concat([df1.drop(columns=['f2_mz_health_facility', 'f2_mz_village']), df2.drop(columns=['f2_mz_health_facility', 'f2_mz_village']), df3.drop(columns=['f2_mz_health_facility', 'f2_mz_village'])])
                .groupby(by=['f2_mz_nbr', 'f2_mz_loc'])
                .agg({'f2a_participant_id': 'count'})
                .sort_values(by=['f2a_participant_id'], ascending=False))
dff2

In [ ]:
dff2.f2a_participant_id.sum()

In [ ]:
# (dff[dff['f2_mz_village'].isna()].sort_values(by=['f2_mz_nbr', 'f2_mz_loc', 'f2_mz_admin'])
#  .rename(columns={'f2_mz_nbr': 'neighborhood', 'f2_mz_loc': 'locality', 'f2_mz_admin': 'admin post'})
#  .drop(columns='f2_mz_village').to_csv(r"D:/My Drive/mozambique/shapefiles/mozambique_unmapped_participants.csv", index=False))

In [ ]:
# dff2=(pd.concat([df1, df2, df3]).dropna()      
#       .groupby(by=['f2_mz_nbr', 'f2_mz_loc'])
#       .agg({'f2a_participant_id': 'count'})
#       .sort_values(by=['f2_mz_nbr', 'f2_mz_loc']))
# dff2

In [ ]:
# pd.merge(dff, dff2, how='inner', left_on=['f2_ke_village', 'f2_ke_chu'], right_index=True, validate='m:1').to_csv(os.path.join('D:/My Drive', "kenya/kenya_villages_women290523.csv"))

In [ ]:
# dff[(dff['f2_mz_loc']==' Xinavane - Sede') & (dff['f2_mz_nbr']==' Celula Sede ')].sort_values(by='f2_mz_nbr')

In [ ]:
dff2=pd.read_csv(r"D:/My Drive/mozambique/mozambique_villages_women310523.csv")
dff2

In [ ]:
# dff[dff['f2_mz_village'].isna()].to_csv(r"D:/My Drive/mozambique/mozambique_unmapped_participants310523.csv")

In [ ]:
dff1=pd.read_csv(r"D:/My Drive/mozambique/mozambique_villages_women.csv")
dff1

In [ ]:
# (pd.merge(dff1, dff2, how='right', on=['f2_mz_nbr', 'f2_mz_loc'], indicator=True)
# .rename(columns={'f2a_participant_id_x': '# women before', 'f2a_participant_id_y': '# women after'})
# .to_csv(r"D:/My Drive/mozambique/mozambique_villages_women310523.csv", index=False))

In [ ]:
dff3=(pd.merge(dff1, dff2, how='right', on=['f2_mz_nbr', 'f2_mz_loc'], indicator=True)
.rename(columns={'f2a_participant_id_y': '# women'})
.drop(columns='f2a_participant_id_x'))
# .to_csv(r"D:/My Drive/mozambique/mozambique_villages_women310523.csv", index=False))
dff3

In [ ]:
dff3[dff3['neighborhood_code'].notna()]['# women'].sum()

In [ ]:
5601/6031

In [ ]:
dff3['neighborhood_code'].nunique()

## Gambia village mapping

In [ ]:
import os
import pandas as pd
import geopandas as gpd

In [ ]:
root_dir=r"D:\My Drive\PRECISE_surveillance_data\Precise_structured_data_032023\The Gambia"

In [ ]:
df1=pd.read_csv(os.path.join(root_dir, "precise_visit_1_arm_1.csv"))
df2=pd.read_csv(os.path.join(root_dir, "precise_visit_2_arm_1.csv"))
df3=pd.read_csv(os.path.join(root_dir, "birth_mother_arm_1.csv"))

In [ ]:
dff=pd.concat([df1, df2, df3])[['f2a_participant_id', 'f2_gm_village']]
dff

In [ ]:
dff=(dff.groupby(by='f2_gm_village')
     .agg({'f2a_participant_id': 'count'})
     .sort_values(by=['f2a_participant_id'], ascending=False))
dff

In [ ]:
df3=pd.read_excel(os.path.join("D:\My Drive\gambia\shapefiles", "gambia_village_codes.xlsx"))
df3

In [ ]:
dff=(pd.merge(dff, df3, left_on='f2_gm_village', right_on='code', how='inner', validate='1:1')
    .rename(columns={'f2a_participant_id': '# visits', 'code': 'village_code'}))
dff

In [ ]:
dff.to_csv(os.path.join("D:\My Drive\gambia", "gambia_villages_women160623.csv"), index=False)